// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_config.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

@com.google.protobuf.Generated
public interface BigQueryDatasetOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.BigQueryDataset)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Output only. The full resource name of the BigQuery dataset. The DATASET_ID
   * will match the ID of the link, so the link must match the naming
   * restrictions of BigQuery datasets (alphanumeric characters and underscores
   * only).
   *
   * The dataset will have a resource path of
   * "bigquery.googleapis.com/projects/[PROJECT_ID]/datasets/[DATASET_ID]"
   * </pre>
   *
   * <code>string dataset_id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The datasetId.
   */
  java.lang.String getDatasetId();

  /**
   *
   *
   * <pre>
   * Output only. The full resource name of the BigQuery dataset. The DATASET_ID
   * will match the ID of the link, so the link must match the naming
   * restrictions of BigQuery datasets (alphanumeric characters and underscores
   * only).
   *
   * The dataset will have a resource path of
   * "bigquery.googleapis.com/projects/[PROJECT_ID]/datasets/[DATASET_ID]"
   * </pre>
   *
   * <code>string dataset_id = 1 [(.google.api.field_behavior) = OUTPUT_ONLY];</code>
   *
   * @return The bytes for datasetId.
   */
  com.google.protobuf.ByteString getDatasetIdBytes();
}
