// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_config.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

@com.google.protobuf.Generated
public interface CopyLogEntriesResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.CopyLogEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Number of log entries copied.
   * </pre>
   *
   * <code>int64 log_entries_copied_count = 1;</code>
   *
   * @return The logEntriesCopiedCount.
   */
  long getLogEntriesCopiedCount();
}
