// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_config.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

@com.google.protobuf.Generated
public interface CreateViewRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.CreateViewRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The bucket in which to create the view
   *
   * `"projects/[PROJECT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]"`
   *
   * For example:
   *
   * `"projects/my-project/locations/global/buckets/my-bucket"`
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The parent.
   */
  java.lang.String getParent();

  /**
   *
   *
   * <pre>
   * Required. The bucket in which to create the view
   *
   * `"projects/[PROJECT_ID]/locations/[LOCATION_ID]/buckets/[BUCKET_ID]"`
   *
   * For example:
   *
   * `"projects/my-project/locations/global/buckets/my-bucket"`
   * </pre>
   *
   * <code>string parent = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for parent.
   */
  com.google.protobuf.ByteString getParentBytes();

  /**
   *
   *
   * <pre>
   * Required. A client-assigned identifier such as `"my-view"`. Identifiers are
   * limited to 100 characters and can include only letters, digits,
   * underscores, hyphens, and periods.
   * </pre>
   *
   * <code>string view_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The viewId.
   */
  java.lang.String getViewId();

  /**
   *
   *
   * <pre>
   * Required. A client-assigned identifier such as `"my-view"`. Identifiers are
   * limited to 100 characters and can include only letters, digits,
   * underscores, hyphens, and periods.
   * </pre>
   *
   * <code>string view_id = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The bytes for viewId.
   */
  com.google.protobuf.ByteString getViewIdBytes();

  /**
   *
   *
   * <pre>
   * Required. The new view.
   * </pre>
   *
   * <code>.google.logging.v2.LogView view = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return Whether the view field is set.
   */
  boolean hasView();

  /**
   *
   *
   * <pre>
   * Required. The new view.
   * </pre>
   *
   * <code>.google.logging.v2.LogView view = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   *
   * @return The view.
   */
  com.google.logging.v2.LogView getView();

  /**
   *
   *
   * <pre>
   * Required. The new view.
   * </pre>
   *
   * <code>.google.logging.v2.LogView view = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  com.google.logging.v2.LogViewOrBuilder getViewOrBuilder();
}
