// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_metrics.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

@com.google.protobuf.Generated
public interface DeleteLogMetricRequestOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.DeleteLogMetricRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Required. The resource name of the metric to delete:
   *
   * "projects/[PROJECT_ID]/metrics/[METRIC_ID]"
   * </pre>
   *
   * <code>
   * string metric_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The metricName.
   */
  java.lang.String getMetricName();

  /**
   *
   *
   * <pre>
   * Required. The resource name of the metric to delete:
   *
   * "projects/[PROJECT_ID]/metrics/[METRIC_ID]"
   * </pre>
   *
   * <code>
   * string metric_name = 1 [(.google.api.field_behavior) = REQUIRED, (.google.api.resource_reference) = { ... }
   * </code>
   *
   * @return The bytes for metricName.
   */
  com.google.protobuf.ByteString getMetricNameBytes();
}
