// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_config.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

/**
 *
 *
 * <pre>
 * IndexType is used for custom indexing. It describes the type of an indexed
 * field.
 * </pre>
 *
 * Protobuf enum {@code google.logging.v2.IndexType}
 */
@com.google.protobuf.Generated
public enum IndexType implements com.google.protobuf.ProtocolMessageEnum {
  /**
   *
   *
   * <pre>
   * The index's type is unspecified.
   * </pre>
   *
   * <code>INDEX_TYPE_UNSPECIFIED = 0;</code>
   */
  INDEX_TYPE_UNSPECIFIED(0),
  /**
   *
   *
   * <pre>
   * The index is a string-type index.
   * </pre>
   *
   * <code>INDEX_TYPE_STRING = 1;</code>
   */
  INDEX_TYPE_STRING(1),
  /**
   *
   *
   * <pre>
   * The index is a integer-type index.
   * </pre>
   *
   * <code>INDEX_TYPE_INTEGER = 2;</code>
   */
  INDEX_TYPE_INTEGER(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 33,
        /* patch= */ 0,
        /* suffix= */ "",
        "IndexType");
  }

  /**
   *
   *
   * <pre>
   * The index's type is unspecified.
   * </pre>
   *
   * <code>INDEX_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int INDEX_TYPE_UNSPECIFIED_VALUE = 0;

  /**
   *
   *
   * <pre>
   * The index is a string-type index.
   * </pre>
   *
   * <code>INDEX_TYPE_STRING = 1;</code>
   */
  public static final int INDEX_TYPE_STRING_VALUE = 1;

  /**
   *
   *
   * <pre>
   * The index is a integer-type index.
   * </pre>
   *
   * <code>INDEX_TYPE_INTEGER = 2;</code>
   */
  public static final int INDEX_TYPE_INTEGER_VALUE = 2;

  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static IndexType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static IndexType forNumber(int value) {
    switch (value) {
      case 0:
        return INDEX_TYPE_UNSPECIFIED;
      case 1:
        return INDEX_TYPE_STRING;
      case 2:
        return INDEX_TYPE_INTEGER;
      default:
        return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<IndexType> internalGetValueMap() {
    return internalValueMap;
  }

  private static final com.google.protobuf.Internal.EnumLiteMap<IndexType> internalValueMap =
      new com.google.protobuf.Internal.EnumLiteMap<IndexType>() {
        public IndexType findValueByNumber(int number) {
          return IndexType.forNumber(number);
        }
      };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }

  public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
    return getDescriptor();
  }

  public static com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
    return com.google.logging.v2.LoggingConfigProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final IndexType[] VALUES = values();

  public static IndexType valueOf(com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private IndexType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:google.logging.v2.IndexType)
}
