// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_metrics.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

@com.google.protobuf.Generated
public interface ListLogMetricsResponseOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.ListLogMetricsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * A list of logs-based metrics.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogMetric metrics = 1;</code>
   */
  java.util.List<com.google.logging.v2.LogMetric> getMetricsList();

  /**
   *
   *
   * <pre>
   * A list of logs-based metrics.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogMetric metrics = 1;</code>
   */
  com.google.logging.v2.LogMetric getMetrics(int index);

  /**
   *
   *
   * <pre>
   * A list of logs-based metrics.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogMetric metrics = 1;</code>
   */
  int getMetricsCount();

  /**
   *
   *
   * <pre>
   * A list of logs-based metrics.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogMetric metrics = 1;</code>
   */
  java.util.List<? extends com.google.logging.v2.LogMetricOrBuilder> getMetricsOrBuilderList();

  /**
   *
   *
   * <pre>
   * A list of logs-based metrics.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogMetric metrics = 1;</code>
   */
  com.google.logging.v2.LogMetricOrBuilder getMetricsOrBuilder(int index);

  /**
   *
   *
   * <pre>
   * If there might be more results than appear in this response, then
   * `nextPageToken` is included. To get the next set of results, call this
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();

  /**
   *
   *
   * <pre>
   * If there might be more results than appear in this response, then
   * `nextPageToken` is included. To get the next set of results, call this
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   *
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString getNextPageTokenBytes();
}
