// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/logging/v2/logging_config.proto
// Protobuf Java Version: 4.33.0

package com.google.logging.v2;

@com.google.protobuf.Generated
public interface LocationMetadataOrBuilder
    extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.LocationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   *
   *
   * <pre>
   * Indicates whether or not Log Analytics features are supported in the given
   * location.
   * </pre>
   *
   * <code>bool log_analytics_enabled = 1;</code>
   *
   * @return The logAnalyticsEnabled.
   */
  boolean getLogAnalyticsEnabled();
}
