bumpMinorPreMajor: true
handleGHRelease: true
releaseType: java-yoshi
branches:
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-yoshi
    branch: java7
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    branch: 3.7.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    extraFiles:
      - >-
        google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java
    branch: 3.13.x
  - bumpMinorPreMajor: true
    handleGHRelease: true
    releaseType: java-backport
    extraFiles:
      - >-
        google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java
    branch: 3.17.x
extraFiles:
  - >-
    google-cloud-logging/src/main/java/com/google/cloud/logging/Instrumentation.java
