// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging_config.proto

// Protobuf Java Version: 3.25.3
package com.google.logging.v2;

public interface CopyLogEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.CopyLogEntriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Number of log entries copied.
   * </pre>
   *
   * <code>int64 log_entries_copied_count = 1;</code>
   * @return The logEntriesCopiedCount.
   */
  long getLogEntriesCopiedCount();
}
