// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging_config.proto

// Protobuf Java Version: 3.25.3
package com.google.logging.v2;

public interface CopyLogEntriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.CopyLogEntriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Log bucket from which to copy log entries.
   *
   * For example:
   *
   *   `"projects/my-project/locations/global/buckets/my-source-bucket"`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Required. Log bucket from which to copy log entries.
   *
   * For example:
   *
   *   `"projects/my-project/locations/global/buckets/my-source-bucket"`
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Optional. A filter specifying which log entries to copy. The filter must be
   * no more than 20k characters. An empty filter matches all log entries.
   * </pre>
   *
   * <code>string filter = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The filter.
   */
  java.lang.String getFilter();
  /**
   * <pre>
   * Optional. A filter specifying which log entries to copy. The filter must be
   * no more than 20k characters. An empty filter matches all log entries.
   * </pre>
   *
   * <code>string filter = 3 [(.google.api.field_behavior) = OPTIONAL];</code>
   * @return The bytes for filter.
   */
  com.google.protobuf.ByteString
      getFilterBytes();

  /**
   * <pre>
   * Required. Destination to which to copy log entries.
   * </pre>
   *
   * <code>string destination = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The destination.
   */
  java.lang.String getDestination();
  /**
   * <pre>
   * Required. Destination to which to copy log entries.
   * </pre>
   *
   * <code>string destination = 4 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for destination.
   */
  com.google.protobuf.ByteString
      getDestinationBytes();
}
