// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging_config.proto

// Protobuf Java Version: 3.25.3
package com.google.logging.v2;

public interface ListLinksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.ListLinksResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of links.
   * </pre>
   *
   * <code>repeated .google.logging.v2.Link links = 1;</code>
   */
  java.util.List<com.google.logging.v2.Link> 
      getLinksList();
  /**
   * <pre>
   * A list of links.
   * </pre>
   *
   * <code>repeated .google.logging.v2.Link links = 1;</code>
   */
  com.google.logging.v2.Link getLinks(int index);
  /**
   * <pre>
   * A list of links.
   * </pre>
   *
   * <code>repeated .google.logging.v2.Link links = 1;</code>
   */
  int getLinksCount();
  /**
   * <pre>
   * A list of links.
   * </pre>
   *
   * <code>repeated .google.logging.v2.Link links = 1;</code>
   */
  java.util.List<? extends com.google.logging.v2.LinkOrBuilder> 
      getLinksOrBuilderList();
  /**
   * <pre>
   * A list of links.
   * </pre>
   *
   * <code>repeated .google.logging.v2.Link links = 1;</code>
   */
  com.google.logging.v2.LinkOrBuilder getLinksOrBuilder(
      int index);

  /**
   * <pre>
   * If there might be more results than those appearing in this response, then
   * `nextPageToken` is included. To get the next set of results, call the same
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * If there might be more results than those appearing in this response, then
   * `nextPageToken` is included. To get the next set of results, call the same
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
