// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging_config.proto

package com.google.logging.v2;

public interface ListViewsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.ListViewsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * A list of views.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogView views = 1;</code>
   */
  java.util.List<com.google.logging.v2.LogView> 
      getViewsList();
  /**
   * <pre>
   * A list of views.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogView views = 1;</code>
   */
  com.google.logging.v2.LogView getViews(int index);
  /**
   * <pre>
   * A list of views.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogView views = 1;</code>
   */
  int getViewsCount();
  /**
   * <pre>
   * A list of views.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogView views = 1;</code>
   */
  java.util.List<? extends com.google.logging.v2.LogViewOrBuilder> 
      getViewsOrBuilderList();
  /**
   * <pre>
   * A list of views.
   * </pre>
   *
   * <code>repeated .google.logging.v2.LogView views = 1;</code>
   */
  com.google.logging.v2.LogViewOrBuilder getViewsOrBuilder(
      int index);

  /**
   * <pre>
   * If there might be more results than appear in this response, then
   * `nextPageToken` is included. To get the next set of results, call the same
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The nextPageToken.
   */
  java.lang.String getNextPageToken();
  /**
   * <pre>
   * If there might be more results than appear in this response, then
   * `nextPageToken` is included. To get the next set of results, call the same
   * method again using the value of `nextPageToken` as `pageToken`.
   * </pre>
   *
   * <code>string next_page_token = 2;</code>
   * @return The bytes for nextPageToken.
   */
  com.google.protobuf.ByteString
      getNextPageTokenBytes();
}
