// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging_config.proto

package com.google.logging.v2;

public interface LocationMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.LocationMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indicates whether or not Log Analytics features are supported in the given
   * location.
   * </pre>
   *
   * <code>bool log_analytics_enabled = 1;</code>
   * @return The logAnalyticsEnabled.
   */
  boolean getLogAnalyticsEnabled();
}
