// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/logging/v2/logging.proto

// Protobuf Java Version: 3.25.3
package com.google.logging.v2;

public interface WriteLogEntriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.logging.v2.WriteLogEntriesResponse)
    com.google.protobuf.MessageOrBuilder {
}
